name: Bulk pack processor CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_DIRECTORY: ./

jobs:
  build:
    name: Build Bulk Pack Processor
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm clean install
        run: npm ci
        working-directory: ${{ env.PROJECT_DIRECTORY }}
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build snapshot with git sha and push on merge
        id: docker_build_snapshot_merge
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: greenstand/${{ github.event.repository.name }}:${{ steps.package-version.outputs.current-version }}
      - name: Build snapshot and push on merge
        id: docker_build_merge
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: greenstand/${{ github.event.repository.name }}:latest
      - shell: bash
        run: |
          echo '${{ steps.package-version.outputs.current-version }}' > image-tag
      - name: persist tag name
        uses: actions/upload-artifact@v1
        with:
          name: image-tag-${{github.sha}}
          path: image-tag

  deploy:
    name: Deploy latest to development environment
    runs-on: ubuntu-latest
    needs: build
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') &&
      github.event_name == 'push' &&
      github.repository_owner == 'Greenstand'
    steps:
      - uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./
      - name: Download tag name
        uses: actions/download-artifact@v1
        with:
          name: image-tag-${{github.sha}}
      - name: Set image tag name
        id: image-tag-name
        run: |
          value=`cat image-tag-${{github.sha}}/image-tag`
          echo "::set-output name=image-tag-name::$value"
      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - name: Run kustomize
        run: (cd deployment/base && ../../kustomize edit set image greenstand/${{ github.event.repository.name }}:${{ steps.image-tag-name.outputs.image-tag-name }} )
      - name: Install doctl for kubernetes
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DEV_CLUSTER_NAME }}
      - name: Update kubernetes resources
        run: kubectl apply -n bulk-pack-services --wait -k ./deployment/base
